version: 2.1

jobs:
  timeout: 240m
  compile:
   docker:
    - image: arifjenong/rom:cirrus
      auth:
          username: arifjenong
          password: $DOCKER_HUB_PWD
   resource_class: large
   steps: 
      - run:
          context: $rclone_config
          command: |
           mkdir lineage-19.1
           mkdir znxt
           mkdir -p $CIRCLE_WORKING_DIRECTORY/.config/rclone
           ls -lh
           echo $rclone_config > $CIRCLE_WORKING_DIRECTORY/.config/rclone/rclone.conf
           ls $CIRCLE_WORKING_DIRECTORY/.config/rclone
           rclone copy znxtproject:ccache/lineage-19.1/ccache.tar.gz $CIRCLE_WORKING_DIRECTORY/znxt -P
           #cd znxt
           #time tar xf ccache.tar.gz
           #rm ccache.tar.gz
           #time rclone copy znxtproject:ccache/lineage-19.1/out.tar.gz lineage-19.1 -P
           #cd lineage-19.1
           #time tar xf out.tar.gz
           #rm -rf out.tar.gz
           #sleep 13m
           #cd lineage-19.1
           #ls -lh
           ls -lh
           cd lineage-19.1
           ls -lh
           git config --global user.name "ariffjenong"
           git config --global user.email "arifbuditantodablekk@gmail.com"
           repo init --depth=1 --no-repo-verify -u https://github.com/ariffjenong/android.git -b lineage-19.1 -g default,-mips,-darwin,-notdefault
           git clone https://github.com/ariffjenong/local_manifest.git --depth=1 -b LOS19 .repo/local_manifests
           repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j12 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
           . build/envsetup.sh
           lunch lineage_maple_dsds-userdebug
           export SELINUX_IGNORE_NEVERALLOWS=true
           export CCACHE_DIR=znxt/ccache
           export CCACHE_EXEC=$(which ccache)
           export USE_CCACHE=1
           ccache -M 15G
           ccache -z
           export ALLOW_MISSING_DEPENDENCIES=true
           export WITH_GMS=false
           export BUILD_HOSTNAME=ArifJeNong
           export BUILD_USERNAME=ArifJeNong
           export TZ=Asia/Jakarta
           #curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="$(echo "${var_cache_report_config}")"
           #make sepolicy -j24
           #make bootimage -j24
           #make init -j24
           #make services
           #make bacon -j24 &  #dont remove that '&'
           #sleep 50m #first running
           #sleep 90m #second running
           #sleep 103m #third running
           #kill %1
           
           make bacon -j12
           #curl -s https://api.telegram.org/$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Build $(cd $ROM_PROJECT/out/target/product/maple_dsds/ && ls *maple*UNOFFICIAL*.zip) Completed!"


            
           ccache -s
           #bash build.sh
           cd out/target/product/maple_dsds
           ls -lh
           rclone copy $(ls *maple*UNOFFICIAL*.zip) znxtproject:rom/lineage-19.1 -P && rclone copy $(ls *.md5sum) znxtproject:rom/lineage-19.1 -P && ls -lh
           #bash build_zip.sh
           #bash sf.sh
           cd ../../../.. && rm -rf lineage-19.1 && rm -rf znxt
           
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile