version: 2.1

jobs:
  timeout: 240m
  compile:
   docker:
    - image: ubuntu:focal
   resource_class: large
   steps: 
      - run:
          command: |
           ls -lh
           bash Dockerfile.sh
           
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile